### ISSUE TITLE
Initialize variables prior to extraction

### ISSUE THREAD

**Issue by blfox** [kartik-v/yii2-tree-manager#35]
Hi Kartik
TreeView widget, add "new Root" - error: "name":"PHP Notice","message":"Undefined variable: formOptions","code":8,"type":"yii\\base\\ErrorException"
,"file":".../vendor/kartik-v/yii2-tree-manager/controllers/NodeController.php","line":83

**Comment by MariusRumpf** [comment]
Had the same issue with `error_reporting(-1);`, when using `error_reporting(E_ALL & ~E_NOTICE);` thinks worked for me.
There are multiple notices thrown, even this `$formOptions` notice is fixed.

**Comment by blfox** [comment]
When commenting formOptions in NodeController.php on line 83, the mold is opened normally. If not comment - I receive an error: NetworkError: 500 Internal Server Error, a variable is not defined it turns?

**Comment by blfox** [comment]
When adding a new field and try to add the root, changes are written only for adding a field, the field name is not changed, the error does not write

**Comment by blfox** [comment]
With the added field figured out, everything works perfectly! There was a problem with the $ formOptions, now just comment out this line, but not sure it's the right way.

**Comment by kartik-v** [comment]
Do you have the latest code (cross check with dev-master)?

Can you try this on [demo page](http://demos.krajee.com/tree-manager-demo/tree-view) and see if you face any error?

**Comment by blfox** [comment]
Tried resetting by the complete removal of the vendor folders Kartik-v/yii2-tree-manager and re-installation of dev-master, an error is (

**Comment by kartik-v** [comment]
The `formOptions` is received via ajax and the `extract` method of PHP. There are more other variables so even if they are not defined they should be fetched via `extract` method of PHP. 

So you should not be facing this error ideally. I will try to anyway explicitly define if you have PHP Error logging set to STRICT.

**Comment by MariusRumpf** [comment]
Please note that these are "only" notices. These occur since $formOptions is not set every time, and not beeing checked with `isset()` or similar. Commenting the line out will result in $formOptions not being passed at all, which leads to errors. 

I see this notices with `error_reporting = -1`, Yii 2.0.4, PHP 5.6.7, yii2-tree-manager v1.0.1, debian75-x64.

When disabling notices in server settings everything works fine. Yii does not proceed if notice is thrown and answers with error 500 on ajax request otherwise.

Say you replace the line with
```php 
'formOptions' => ((isset($formOptions)) ? Json::decode($formOptions) : ''),
```
the notice is gone but you get 
```
exception 'yii\base\ErrorException' with message 'Undefined variable: nodeAddlViews' in /var/www/synfo/vendor/kartik-v/yii2-tree-manager/controllers/NodeController.php:94
```

replace that with 
```php 
'nodeAddlViews' => ((isset($nodeAddlViews)) ? $nodeAddlViews : ''),
````

and so on.

This notices result from variables not being initialized.

**Comment by kartik-v** [comment]
Ok I pushed in an enhancement to just initialize the variables before extraction.

Changed the issue title.

**Comment by blfox** [comment]
kartik-v,  MariusRumpf 
Thank you for your prompt assistance!

**Comment by robotE13** [comment]
The problem is still not solved. Now an exception is thrown because the Json::decode in line 103 is passed argument of the wrong type. $formOptions initialize before extraction as array ($formOptions = []; line 81). Helped replacement for $formOptions = Json::encode([]);

**Comment by kartik-v** [comment]
While this can be initialized to a `{}`... I am not sure why you are facing an exception. The PHP `extract` should replace `formOptions` with a json encoded string.

**Comment by kartik-v** [comment]
Anyway there is an enh via #38 which should resolve any other empty values passed to formOptions.
